---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-repo-pvc
  namespace: web-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
