apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-backup
  namespace: kube-system
spec:
  concurrencyPolicy: Forbid
  schedule: '5 * * * *' # Run at the minute  of every hour
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: etcd-backup-talos
          nodeSelector:
            node-role.kubernetes.io/control-plane: ''
          tolerations:
            - key: 'node-role.kubernetes.io/control-plane'
              operator: 'Exists'
              effect: 'NoSchedule'
          initContainers:
            - name: talosctl
              image: ghcr.io/siderolabs/talosctl:v1.9.5
              args:
                - --talosconfig=/var/run/secrets/talos.dev/talosconfig
                - --endpoints=$(CP_NODE_IP)
                - -n
                - '$(CP_NODE_IP)'
                - etcd
                - snapshot
                - /data/etcd.snapshot
              env:
                - name: CP_NODE_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
              volumeMounts:
                - name: talos-secrets
                  mountPath: /var/run/secrets/talos.dev
                - name: backupdata
                  mountPath: /data
          containers:
            - name: gzip
              image: alpine:latest
              command:
                - /bin/sh
                - -c
                - |
                  gzip -c /data/etcd.snapshot > /data/etcd-$(date +%Y%m%d-%H%M%S).snapshot.gz
              volumeMounts:
                - name: backupdata
                  mountPath: /data
          volumes:
            - name: backupdata
              persistentVolumeClaim:
                claimName: etcd-backup-data
            - name: talos-secrets
              secret:
                secretName: etcd-backup-talos-secrets
          restartPolicy: OnFailure
