---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-backup-data
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: nfs
