kind: Blueprint
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: homelab
  description: This blueprint outlines resources in the homelab context
repository:
  url: https://github.com/hernan82arg/homelab.git
  ref:
    branch: main
  secretName: flux-system
sources:
  - name: core
    url: github.com/windsorcli/core
    ref:
      branch: main
terraform:
  - source: core
    path: cluster/talos
  - source: core
    path: gitops/flux
    destroy: false
  - path: base
    destroy: false
  - path: tapo
    destroy: false
kustomize:
  - name: telemetry-base
    path: telemetry/base
    source: core
    components:
      - prometheus
      - prometheus/flux
  - name: telemetry-resources
    path: telemetry/resources
    source: core
    dependsOn:
      - telemetry-base
    components:
      - metrics-server
      - prometheus
      - prometheus/flux
  - name: policy-base
    path: policy/base
    source: core
    components:
      - kyverno
  - name: policy-resources
    path: policy/resources
    source: core
    dependsOn:
      - policy-base
  - name: csi
    path: csi
    source: core
    dependsOn:
      - policy-resources
    force: true
    components:
      - openebs
      - openebs/dynamic-localpv
  - name: lb-base
    path: lb/base
    source: core
    dependsOn:
      - policy-resources
    force: true
    components:
      - metallb
  - name: lb-resources
    path: lb/resources
    source: core
    dependsOn:
      - lb-base
    force: true
    components:
      - metallb/layer2
  - name: ingress
    path: ingress
    source: core
    dependsOn:
      - pki-resources
    force: true
    components:
      - nginx
      - nginx/loadbalancer
      - nginx/coredns
      - nginx/flux-webhook
      - nginx/web
  - name: pki-base
    path: pki/base
    source: core
    dependsOn:
      - policy-resources
    force: true
    components:
      - cert-manager
      - trust-manager
  - name: pki-resources
    path: pki/resources
    source: core
    dependsOn:
      - pki-base
    force: true
    components:
      - private-issuer/ca
      - public-issuer/selfsigned
  - name: dns
    path: dns
    source: core
    dependsOn:
      - pki-base
    force: true
    components:
      - coredns
      - coredns/etcd
      - external-dns
      - external-dns/coredns
      - external-dns/ingress
    patches:
      - patch: |
          apiVersion: helm.toolkit.fluxcd.io/v2beta1
          kind: HelmRelease
          metadata:
            name: coredns
            namespace: system-dns
          spec:
            values:
              nodeSelector:
                node-role.kubernetes.io/control-plane: ""
              tolerations:
                - key: "node-role.kubernetes.io/control-plane"
                  operator: "Exists"
                  effect: "NoSchedule"
        target:
          kind: HelmRelease
          namespace: system-dns
          name: coredns
      - patch: |
          apiVersion: helm.toolkit.fluxcd.io/v2beta1
          kind: HelmRelease
          metadata:
            name: external-dns
            namespace: system-dns
          spec:
            values:
              nodeSelector:
                node-role.kubernetes.io/control-plane: ""
              tolerations:
                - key: "node-role.kubernetes.io/control-plane"
                  operator: "Exists"
                  effect: "NoSchedule"
        target:
          kind: HelmRelease
          namespace: system-dns
          name: external-dns
  - name: gitops
    path: gitops/flux
    source: core
    dependsOn:
      - ingress
    force: true
    components:
      - webhook
  - name: observability
    path: observability
    source: core
    dependsOn:
      - csi
      - ingress
    components:
      - grafana
      - grafana/ingress
      - grafana/prometheus
      - grafana/node
      - grafana/kubernetes
      - grafana/flux
  - name: nfs-csi
    path: base/nfs-csi
    dependsOn:
      - pki-base
    force: true
  - name: dashboard
    path: base/dashboard
    dependsOn:
      - pki-base
      - ingress
    force: true
  - name: etcd-backup
    path: base/etcd-backup
    dependsOn:
      - pki-base
    force: true
  - name: elasticsearch
    path: observability
    source: core
    dependsOn:
      - pki-base
    patches:
      - patch: "apiVersion: helm.toolkit.fluxcd.io/v2beta1\nkind: HelmRelease\nmetadata:\n  name: elasticsearch\n  namespace: system-observability\nspec:\n  values:\n    replicas: 2\n"
        target:
          kind: HelmRelease
          namespace: system-observability
          name: elasticsearch
    force: true
    components:
      - elasticsearch
  - name: kibana
    path: observability
    source: core
    dependsOn:
      - pki-base
      - elasticsearch
      - ingress
    patches:
      - patch: "apiVersion: helm.toolkit.fluxcd.io/v2beta1\nkind: HelmRelease\nmetadata:\n  name: kibana\n  namespace: system-observability\nspec:\n  values:\n    nodeSelector:\n      node-role.kubernetes.io/control-plane: \"\"\n    tolerations:\n      - key: \"node-role.kubernetes.io/control-plane\"\n        operator: \"Exists\"\n        effect: \"NoSchedule\"\n"
    force: true
    components:
      - kibana
      - kibana/ingress
  - name: filebeat
    path: telemetry/base
    source: core
    dependsOn:
      - pki-base
      - elasticsearch
    patches:
      - patch: "apiVersion: helm.toolkit.fluxcd.io/v2beta1\nkind: HelmRelease\nmetadata:\n  name: filebeat\n  namespace: system-telemetry\nspec:\n  values:\n    resources:\n      requests:\n        cpu: \"200m\"\n        memory: \"500M\"\n      limits:\n        cpu: \"1000m\"\n        memory: \"1500M\"\n"
    force: true
    components:
      - filebeat
  - name: local-path
    path: base/local-path-csi
    dependsOn:
      - pki-base
  - name: kubevirt
    path: kubevirt
    dependsOn:
      - local-path
  - name: data
    path: data
    dependsOn:
      - csi
    force: true
    components:
      - redis
      - postgres/cloudnativepg
  - name: tapo-api
    path: tapo/api
    dependsOn:
      - pki-base
    force: true
  - name: tapo-web
    path: tapo/web
    dependsOn:
      - pki-base
    force: true
  - name: web-repo
    path: web-repo
    dependsOn:
      - pki-base
      - ingress
    force: true
