platform: metal
network:
  loadbalancer_driver: kube-vip
  loadbalancer_ips:
    start: 192.168.1.200
    end: 192.168.1.210
terraform:
  enabled: true
  backend:
    type: local
cluster:
  enabled: true
  driver: talos
  endpoint: 192.168.1.27
  workers:
    volumes:
      - local:/var/lib/openebs
dns:
  domain: homelab.local
