---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 10m
  url: https://prometheus-community.github.io/helm-charts
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "70.3.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  values:
    prometheus:
      prometheusSpec:
        retention: 7d
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
    grafana:
      enabled: true
      persistence:
        enabled: true
        size: 10Gi
    alertmanager:
      enabled: true
      alertmanagerSpec:
        retention: 120h
