apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: allow-blackbox-exporter-no-digest
  namespace: system-telemetry
spec:
  exceptions:
  - policyName: require-image-digest
    ruleNames:
    - autogen-validate-containers
    - validate-containers
  match:
    any:
    - resources:
        kinds:
        - Deployment
        namespaces:
        - system-telemetry
        names:
        - blackbox-exporter-prometheus-blackbox-exporter
