---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-internal
  namespace: system-telemetry
spec:
  interval: 30s
  module: http_2xx
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.system-telemetry.svc.cluster.local:9115
    path: /probe
  targets:
    staticConfig:
      static:
        - http://grafana.system-observability.svc.cluster.local/login
        - http://image-web-server.web-server.svc.cluster.local
        - http://tapo-web.tapo.svc.cluster.local
