apiVersion: apps/v1
kind: Deployment
metadata:
  name: tapo-rest
  namespace: tapo
  labels:
    app: tapo-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tapo-rest
  template:
    metadata:
      labels:
        app: tapo-rest
    spec:
      containers:
      - name: tapo-rest
        image: ghcr.io/hernan82arg/tapo-rest:latest
        command: ["/app/tapo-rest"]
        args: ["/app/devices.json"]
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: tapo-credentials
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi" 
            cpu: "100m"
