apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - runner-deployment.yaml
  - general-utility-runner.yaml
  - controller-manager.yaml
  - onepassword-token.yaml
  - namespace.yaml
