---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 10m
  url: https://kubernetes-sigs.github.io/metrics-server/
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: metrics-server
      version: "3.12.2"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: kube-system
  values:
    args:
      - --kubelet-insecure-tls
    metrics:
      enabled: true
