---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: windows11
  namespace: default
spec:
  source:
    http:
      url: 'http://image-web-server.web-server.svc.cluster.local/windows11-disk.qcow2'
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 65Gi
    storageClassName: single
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: windows11-vm
  namespace: default
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/domain: windows11-vm
    spec:
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 2
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: sata
          interfaces:
            - bridge: {}
              model: e1000
              name: default
              ports:
                - name: rdp
                  port: 3389
          tpm: {}
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
          smm: {}
        firmware:
          bootloader:
            efi:
              secureBoot: true
          uuid: 5d307ca9-b3ef-428c-8861-06e72d69f222
        resources:
          requests:
            memory: 4Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: windows11
      terminationGracePeriodSeconds: 0
