---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-nfs
  namespace: system-gitops
spec:
  interval: 10m
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  timeout: 3m
