---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: system-csi
spec:
  interval: 5m
  chart:
    spec:
      chart: csi-driver-nfs
      version: v4.10.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: system-gitops
      interval: 5m
  values:
    controller:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
